### ISSUE TITLE
No sentences found! Change language or add database!  Version ⁨2.1.49 (dc80804a)⁩

### ISSUE THREAD

**Issue by immunekang** [krmanik/Sentence-Adder-Anki-Addon#10]
I can't get the add-on to work on my mac os 11.6.5.  I had used this app before.  I deleted and added the add-on and tsv database several times.  Im not sure what is happening.  Any ideas?

**Comment by krmanik** [comment]
I have to test it locally on my mac os. I will let you know later.
Which Anki Version you are using?

**Comment by immunekang** [comment]
Thank you.  I am using version 2.1.49.

**Comment by krmanik** [comment]
Hi, I have updated the addons, try it the bug is fixes and also more features added.
Also please provide feedback for improvements.


**Note:** If already created the sentences database then save a copy of `lang_db` and `config.json` folder from `Anki2/addons21/1682655437/` into `Anki2/addons21/1682655437/user_files/`

**Comment by immunekang** [comment]
Hi, I am using Anki 2.1.53 and running mac os Big Sur version 11.6.7.   This is the new message I am getting.
![Screen Shot 2022-06-19 at 19 39 44](https://user-images.githubusercontent.com/62669416/174493725-ef93940f-f15b-45ff-bb21-faaebe0dae26.png)

**Comment by krmanik** [comment]
Hi, there is check option for `Sentences contain spaces` check it for _English_ language because CJK language does not contains generally. 

![image](https://user-images.githubusercontent.com/12841290/174661367-0202cceb-e6e6-40d0-b04e-c4221be7d0e8.png)

**Comment by krmanik** [comment]
You table does not contains sentences, because it sentences pairs files, it is not implemented yet. In next version it will be implemented.
![image](https://user-images.githubusercontent.com/12841290/175362541-a391fcd2-4680-48db-ba26-106f44782f4b.png)

**Comment by immunekang** [comment]
Ahh,  so I must only Download sentences from a given language and not language pairs.  I’m sorry for my confusion and thank you for your help.  I’m looking forward to the sentence pair option in the next version.  Thank your very much!
