### ISSUE TITLE
Chinese - Not finding sentences

### ISSUE THREAD

**Issue by yaoberh** [krmanik/Sentence-Adder-Anki-Addon#13]
Something strange is happening when I try to bulk add sentences for a list of words.
The words have sentences in my tsv file, but the program won't find them and parse them.
This isn't only with Chinese, it also happened with Russian.
It just won't find any sentences at all, and then it will suddenly find others. Don't understand the pattern.

**Comment by yaoberh** [comment]
Oh that makes sense. Would be excellent if this could be implemented

**Comment by krmanik** [comment]
To be implemented in next update
