### ISSUE TITLE
When Will Sentence Pairs Be Available?

### ISSUE THREAD

**Issue by immunekang** [krmanik/Sentence-Adder-Anki-Addon#15]
I downloaded sentence pairs for two langauges and imported into my Anki deck.  I freeze all the cards and then browse for sentences when I need them.  Unfortunately this has maxed out my sync account.  Do you have any idea when the Sentence pairs will be available through your add-on?

**Comment by yaoberh** [comment]
You can just download sentence pairs from tatoeba.
What's that about your sync maxing out? Never had that problem myself

**Comment by immunekang** [comment]
250 MBs is the maximum allowed through anki sync.

**Comment by immunekang** [comment]
yaoberh,  I was told that sentence pairs can't be downloaded for now.  Here is my conversation from earlier. 
![Screen Shot 2022-07-31 at 13 32 32](https://user-images.githubusercontent.com/62669416/182024299-45994647-c53c-4742-9349-6c0fbea063da.png)

**Comment by Nayelianne** [comment]
I'd love this option to be available too!
