### ISSUE TITLE
Bug: DB doesn't work

### ISSUE THREAD

**Issue by darlopvil** [krmanik/Sentence-Adder-Anki-Addon#16]
Hi, 

just installed the add-on, created the db and all cool. The problem begins after restarting Anki to get the changes done. It all looks normal in the add-on configuration window, but this appears when used:
![imagen](https://user-images.githubusercontent.com/60988792/188327456-329aa526-0134-4b0a-8758-c9097dfeda60.png)

So, went deep into the folder path until reached the Anki2 folder… For my surprise, these two "ang_db and config.json" files don't exist there but in the user_files folder. No clue what's going on.

**Comment by krmanik** [comment]
If the language is not Chinese or Japanese then the language may contains space between words so you have turn contains spaces in config option of the addons.
