### ISSUE TITLE
putting any HTML to set the target word apart in a sentence (not just colors)

### ISSUE THREAD

**Issue by daredvz** [krmanik/Sentence-Adder-Anki-Addon#18]
Would it be possible to implement the option adding custom HTML to wrap around the target word (say, if I wanted bold; <b>target word</b>; now there are some tatoeba sentences which already include this so it would probably require to strip formatting from tsv file and then wrap custom formatting around a target word...) and not just the color when in the config? If it has already been added and I did not notice, my bad. Also, I noticed, that even if adding just one sentence, it adds a line break, which has a tendency to multiply and annoy :D ...

I am no programmer and I have not the slightest idea how much work it includes but I was just wondering, I tend to just emphasize the target words with bold.

Anyway, thanks for your work!

**Comment by krmanik** [comment]
This can be done. I will start development/updating this addon soon.
