### ISSUE TITLE
Problem: Selecting from a list of all sentences

### ISSUE THREAD

**Issue by daredvz** [krmanik/Sentence-Adder-Anki-Addon#19]
I have come across an issue, where this happens: When I choose a sentence from a list of all available sentences in tsv file containing the word, the sentence is pasted into the field, but each character is in its own separate line.
![sentence_adder_tatoeba](https://user-images.githubusercontent.com/93817503/209240113-11090132-bffa-49e1-a9fe-e5b88d67e325.jpg)

**Comment by krmanik** [comment]
Is the sentences taken from https://tatoeba.org/en/ ? If possible you zip the csv file and upload here, for further debugging of the issues.
